apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: stage
  source:
    repoURL: https://github.com/53555/argocd.git
    targetRevision: stage
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
