apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    repoURL: https://github.com/53555/argocd.git
    targetRevision: master
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: default
