apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fleetman
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    repoURL: https://raw.githubusercontent.com/53555/helm-repo/master
    targetRevision: "0.3.0"
    chart: fleetman
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
