apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fleetman-prod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    repoURL: https://raw.githubusercontent.com/53555/helm-repo/master
    chart: fleetman
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
